const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const modal=$('#booking-modal'), chat=$('.chat-panel'), video=$('.video-modal');
let booking={care:'Primera evaluación',doctor:'',time:''};
function showStage(n){$$('.booking-stage').forEach(el=>el.classList.toggle('hidden',el.dataset.stage!=n));$$('.booking-progress span').forEach((el,i)=>el.classList.toggle('active',i<Math.min(n,3)));}
function openBooking(route){booking={care:route||'Primera evaluación',doctor:'',time:''};$('#summary-care').textContent=booking.care;showStage(1);modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeBooking(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
$$('.js-book').forEach(b=>b.addEventListener('click',()=>openBooking()));
$$('[data-route]').forEach(b=>b.addEventListener('click',()=>openBooking(b.dataset.route)));
$$('[data-care]').forEach(b=>b.addEventListener('click',()=>{booking.care=b.dataset.care;$('#summary-care').textContent=booking.care;showStage(2)}));
$$('[data-doctor]').forEach(b=>b.addEventListener('click',()=>{$$('[data-doctor]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');booking.doctor=b.dataset.doctor}));
$$('.time-grid button').forEach(b=>b.addEventListener('click',()=>{if(!booking.doctor)booking.doctor='Dra. Azucena';$$('.time-grid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');booking.time=b.textContent;$('#summary-slot').textContent=`${booking.doctor} · ${booking.time}`;setTimeout(()=>showStage(3),180)}));
$('.fake-pay').addEventListener('click',()=>{const btn=$('.fake-pay');btn.textContent='Procesando anticipo…';btn.disabled=true;setTimeout(()=>{showStage(4);btn.textContent='Simular pago y confirmar';btn.disabled=false},900)});
$('.modal-close').addEventListener('click',closeBooking);$('.close-success').addEventListener('click',closeBooking);$('.modal-backdrop',modal).addEventListener('click',closeBooking);
$('.pixie-button').addEventListener('click',()=>{chat.classList.toggle('open');chat.setAttribute('aria-hidden',String(!chat.classList.contains('open')))});$('.chat-head button').addEventListener('click',()=>chat.classList.remove('open'));
function pixieAnswer(question){const body=$('.chat-body');$('.typing').classList.remove('hidden');setTimeout(()=>{ $('.typing').classList.add('hidden');const answers={'Quiero agendar':'¡Claro! Puedo ayudarte a elegir especialista y horario. Pulsa “Agenda tu evaluación” para ver la experiencia demo.','¿Atienden bebés?':'Sí. El cuidado para bebés utiliza ajustes muy suaves y se adapta a cada etapa de desarrollo.','¿Qué es INSiGHT?':'Es tecnología de evaluación que ayuda al equipo a observar patrones del sistema nervioso y explicar los hallazgos con claridad.'};const m=document.createElement('div');m.className='bot-message';m.style.marginTop='12px';m.textContent=answers[question]||'Gracias por tu pregunta. En la versión final podré responder con la base de conocimiento de la clínica y ayudarte a agendar.';body.insertBefore(m,$('.quick-replies'));body.scrollTop=body.scrollHeight},650)}
$$('.quick-replies button').forEach(b=>b.addEventListener('click',()=>pixieAnswer(b.textContent)));$('.chat-input').addEventListener('submit',e=>{e.preventDefault();const input=$('.chat-input input');if(input.value.trim()){pixieAnswer(input.value.trim());input.value=''}});
$('.js-storm').addEventListener('click',()=>{video.classList.add('open');video.setAttribute('aria-hidden','false')});$('.video-close').addEventListener('click',()=>video.classList.remove('open'));$('.modal-backdrop',video).addEventListener('click',()=>video.classList.remove('open'));
$('.menu-toggle').addEventListener('click',e=>{const nav=$('.main-nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(nav.classList.contains('open')))});$$('.main-nav a').forEach(a=>a.addEventListener('click',()=>$('.main-nav').classList.remove('open')));
$$('.story-filter button').forEach(b=>b.addEventListener('click',()=>{$$('.story-filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeBooking();chat.classList.remove('open');video.classList.remove('open')}});
